name: Prod Pipeline (WEBAPP)
on:
  push:
    branches:
      - main

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: sn-aepsy
          minimum-approvals: 1
          issue-title: "DEPLOY BE"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
  otherjob:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: sn-aepsy
          minimum-approvals: 1
          issue-title: "DEPLOY FE"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
